"""The single orchestration class: incident_id in, a validated
InvestigationReport out. This is the ONLY place evidence collection,
prompt construction, the provider call, and output validation are
wired together — deliberately not a generic agent loop (Phase 5 §12):
exactly one pass, no tool use, no iteration, no retries that call the
provider again with a different strategy.
"""

import logging
from datetime import datetime

from investigator_service.config import EvidenceBounds
from investigator_service.domain.investigation import InvestigationReport, MissingEvidence, ProviderMetadata
from investigator_service.evidence_collector import EvidenceCollector
from investigator_service.llm.prompt import build_prompts
from investigator_service.llm.provider import LLMProvider
from investigator_service.llm.validation import parse_and_validate

logger = logging.getLogger("investigator_service.investigator")


class ProviderNotConfiguredError(Exception):
    """No LLM provider is configured (Phase 5 §2/§6). Evidence
    collection may have already succeeded by the time this is raised —
    the caller (api/investigations.py) decides what, if anything, of
    that evidence to surface alongside this explicit, safe
    "unavailable" signal."""


class Investigator:
    def __init__(self, collector: EvidenceCollector, provider: LLMProvider | None, bounds: EvidenceBounds) -> None:
        self._collector = collector
        self._provider = provider
        self._bounds = bounds

    async def investigate(self, incident_id: str):
        """Returns InvestigationReport. Raises (uncaught, for the API
        layer to translate): IncidentNotFoundError, ControlPlaneUnavailableError,
        ProviderNotConfiguredError, PromptTooLargeError, ProviderError, ProviderOutputError."""
        evidence = await self._collector.collect(incident_id)

        if self._provider is None:
            raise ProviderNotConfiguredError()

        system_prompt, user_prompt, shown_ids, omitted_ids = build_prompts(evidence, self._bounds)
        raw_text = await self._provider.investigate(system_prompt, user_prompt)

        # IMPORTANT (Phase 5 correction round #1): validated against
        # the ids actually shown to the model, not every id the larger
        # EvidencePackage happens to contain.
        llm_output, notes = parse_and_validate(raw_text, frozenset(shown_ids))

        # System-synthesized missing-evidence entries -- never
        # generated by the model, so they survive regardless of what
        # it says, and are never confused with its own (also honest,
        # but separately validated) missing_evidence claims.
        missing_evidence = list(llm_output.missing_evidence)
        for outcome in evidence.source_outcomes:
            if outcome.status == "partial":
                missing_evidence.append(
                    MissingEvidence(description=f"{outcome.source}: {outcome.detail}")
                )
        if omitted_ids:
            notes.append(
                f"{len(omitted_ids)} collected evidence item(s) were not shown to the model due to "
                f"the context-size bound: {', '.join(omitted_ids)}"
            )
            missing_evidence.append(
                MissingEvidence(
                    description=(
                        f"{len(omitted_ids)} collected evidence item(s) were omitted from the model's "
                        "context due to the configured size bound and could not factor into its analysis"
                    )
                )
            )

        return InvestigationReport(
            incident_id=evidence.incident.id,
            investigated_at=datetime.now(evidence.incident.first_seen_at.tzinfo),
            incident_status_at_investigation=evidence.incident.status,
            summary=llm_output.summary,
            observations=llm_output.observations,
            hypotheses=llm_output.hypotheses,
            missing_evidence=missing_evidence,
            suggested_checks=llm_output.suggested_checks,
            evidence=evidence.items,
            source_outcomes=evidence.source_outcomes,
            provider=ProviderMetadata(
                configured=True, provider=self._provider.name, model=getattr(self._provider, "model", None)
            ),
            validation_notes=notes,
        )
